// Pokédex Regions with their Pokémon ranges
export const POKEDEX_REGIONS = [
  { name: 'Kanto', generation: 'I', start: 1, end: 151, count: 151 },
  { name: 'Johto', generation: 'II', start: 152, end: 251, count: 100 },
  { name: 'Hoenn', generation: 'III', start: 252, end: 386, count: 135 },
  { name: 'Sinnoh', generation: 'IV', start: 387, end: 493, count: 107 },
  { name: 'Unova', generation: 'V', start: 494, end: 649, count: 156 },
  { name: 'Kalos', generation: 'VI', start: 650, end: 721, count: 72 },
  { name: 'Alola', generation: 'VII', start: 722, end: 809, count: 88 },
  { name: 'Galar', generation: 'VIII', start: 810, end: 898, count: 89 },
  { name: 'Hisui', generation: 'VIII (Legends: Arceus)', start: 899, end: 905, count: 7 },
  { name: 'Paldea', generation: 'IX', start: 906, end: 1025, count: 120 },
];

// Helper function to get region for a given Pokédex number
export const getRegionForPokedexNumber = (pokedexNumber: number): string | null => {
  const region = POKEDEX_REGIONS.find(
    r => pokedexNumber >= r.start && pokedexNumber <= r.end
  );
  return region ? region.name : null;
};

// Default order for Pokédex regions (by generation)
export const DEFAULT_POKEDEX_REGIONS_ORDER = [
  'Kanto',
  'Johto',
  'Hoenn',
  'Sinnoh',
  'Unova',
  'Kalos',
  'Alola',
  'Galar',
  'Hisui',
  'Paldea',
];

export const COLLECTIONS: string[] = [
  "Hits",

  "Sets_Standard",
  "SV_Standard_Repeat",
  
  "Sets_Reverse",
  "SV_Reverse_Repeat",
  "SAS_Pokedex_Reverse",
  
  
  "SV_Holo_Fosa",
  "SV_Holo_Fosa_DC",
  
  "SV_Reverse_Fosa",
  "SV_Reverse_Fosa_DC",
  
  "SAS_Holo_Fosa_DC",
  "SAS_Reverse_Fosa_DC",
  
  "Pokedex_SMSWSH_Binder",
  "Pokedex_SMSWSH_Paldea",
  "Pokedex_SMSWSH_Complement",
  "Pokedex_SMSWSH_Reserva",

  "Pokedex_BW_XY",
  "Pokedex_Ex_DP",
  "Pokedex_E-card",
  "Pokedex_Neo",
  "Pokedex_WoC",

  "Orders",
];



export const LIMITS: { [key: string]: number } = {
  Normal: 1, // Standard SemiSet
  Reverse: 1, //Parallel SemiSet
  Amarillo: 1, // Pokedex Amarilla
  "SAS Reverse Repeat": 1, // Reverses de la Era SAS

  "SV Holo Repeat": 3, // Standard de la Era SV
  "SV Reverse Repeat": 2, // Parallel de la Era SV

  "SV Holo Fosa": 3,
  "SV Reverse Fosa": 3,
  "SAS Holo Fosa": 3,
  "SAS Reverse Fosa": 3,
};

interface DependsItem {
  depends: string;
  setIncludes?: string[];
}

export const DEPENDS: { [key: string]: DependsItem } = {
  "SAS Reverse Fosa": {
    depends: "SAS Reverse Repeat",
  },
  "SAS Reverse Repeat": {
    depends: "Reverse",
    setIncludes: ["Pokémon GO", "Crown Zenith"],
  },

  "SAS Holo Fosa": {
    depends: "Amarillo",
  },
  Amarillo: {
    depends: "Normal",
    setIncludes: ["Pokémon GO", "Crown Zenith"],
  },

  "SV Reverse Fosa": {
    depends: "SV Reverse Repeat",
  },
  "SV Reverse Repeat": {
    depends: "Reverse",
  },

  "SV Holo Fosa": {
    depends: "SV Holo Repeat",
  },
  "SV Holo Repeat": {
    depends: "Normal",
  },
};

export const DEFAULT_ENERGY_TYPES_ORDER = [
  "Grass",
  "Fire",
  "Water",
  "Lightning",
  "Psychic",
  "Fighting",
  "Darkness",
  "Metal",
  "Dragon",
  "Fairy",
  "Colorless",
  "Trainer",
  "Energy",
];

export const POKEMON_FORM_VARIANTS_ORDER = [
  "Shiny",
  "Mega",
  "Gigantamax",
  "Alolan",
  "Galarian",
  "Hisuian",
  "Paldean",
  "Gender Mayor",
  "Origin",
  "Thernian form",
  "Primal",
  "Pikachu Cap",
  "Pikachu Cosplay",
  "Unown",
  "Alcremie form",
  "Arceus form",
  "Silvally form",
  "Vivillon form",
  "Furfrou form",
  "Minior form",
  "Floette form",
  "Flabebe form",
  "Florges form",
  "Rotom form",
  "Deerling form",
  "Deoxys Form",
  "Genesect form",
  "Gourgeist form",
  "Oricorio form",
  "Pumpkaboo form",
  "Sawsbuck form",
  "Urshifu form",
  "Basculin form",
  "Burmy form",
  "Lycanroc form",
  "Wormadam form",
  "Aegislash form",
  "Calyrex form",
  "Cherrim form",
  "Cramorant form",
  "Crowned",
  "Eiscue form",
  "Gastrodon form",
  "Hoopa form",
  "Keldeo form",
  "Kyurem form",
  "Meloetta form",
  "Mimikyu form",
  "Morpeko form",
  "Shaymin form",
  "Shellos form",
  "Toxtricity form",
  "Wishiwashi form",
  "Xerneas form",
  "Greninja form",
  "Magearna form",
  "Marshadow form",
  "Polteageist form",
  "Sinistea form",
  "Ursaluna form",
  "Zarude form",
];

export const DEFAULT_RARITIES_ORDER = [
  "Common",
  "Uncommon",
  "Rare",
  "Rare Holo",

  "Rare Holo V",
  "Double Rare",
  "Rare Holo GX",

  "Rare Holo VMAX",
  "Rare Holo VSTAR",

  "ACE SPEC Rare",

  "Rare Shiny",
  "Illustration Rare",
  "Rare Ultra",
  "Ultra Rare",
  "Alternative",
  "Alternative VMAX",
  "Special Illustration Rare",
  "Secret Gold Reverse",
  "Golden Alternative",
  "Rare Secret",
  "Hyper Rare",
  "Rare Rainbow",

  "Radiant Rare",
  "Amazing Rare",
  "Rare Prism Star",

  "Trainer Gallery Rare Holo",
  "Trainer Gallery Rare Holo V",
  "Trainer Gallery Rare Holo VMAX",
  "Galarian Gallery Rare Holo",
  "Galarian Gallery Rare Holo V",
  "Galarian Gallery Rare Holo VMAX",
  "Galarian Gallery Rare Holo VSTAR",

  "Promo",
  "Real Promo",
  "Prerelease",
  "V-UNION",

  "Rare Shining",
  "Shiny Rare",
  "Rare Shiny GX",
  "Rare Holo V Shiny",
  "Rare Holo VMAX Shiny",
  "Shiny Ultra Rare",
  "Classic Collection",
  "Classic Collection: Metal",
];


export const DEFAULT_VARIANTS_ORDER = [
"Standard",
"1st Edition",
"1st Edition Shadowless",
"Parallel",
"Poké Ball Parallel",
"Master Ball Parallel",
"Ascenced Parallel",
"Stamp",
"Jumbo",
"Battle Academy",
"WC Deck",
"Battle Road",
"Play Pokémon",
"SM Trainer Kit",
"Store Stamp",
"Event Stamp",
"League Challenge",
"Championships",
"Promo Card",
"Error",
"1st Edition",
"1st Edition Holo",
"1st Edition (Shadowless)",
"1st Edition Holo (Shadowless)",
"Normal (Shadowless)",
"Normal Holo (Shadowless)",
"Normal",
"Normal Holo",
"Holo",
"Non-holo",
"Reverse Holo",
"Energy Holo",
"Poké Ball Reverse Holo",
"Master Ball Reverse Holo",
"Expansion Stamp Holo",
"Energy Reverse Holo",
"Friend Ball Reverse Holo",
"Love Ball Reverse Holo",
"Quick Ball Reverse Holo",
"Rocket Reverse Holo",
"Dusk Ball Reverse Holo",
"Promo",
"Pokémon 4Ever Movie",
"Destiny Deoxys Movie",
"Pokémon the First Movie",
"I Choose You! Movie",
"2000 Pikachu World Collection",
"Non-holo (1st Edition Error)",
"Normal (\"6/61\" Card Number Error)",
"Normal (\"damage counters\" Text Error)",
"Normal (\"Phanphy\" Text Error)",
"Normal (Pokédex Entry Error)",
"Normal Holo (Energy Symbol Error)",
"Normal Holo (Evolution Box Error)",
"Reverse Holo (\"Phanphy\" Text Error)",
"Reverse Holo (Pokédex Entry Error)",
"1st Edition (Shadowless) (Red Cheeks)",
"Normal (Shadowless) (Red Cheeks)",
"Black Star Promo Symbol",
"Wizard World Chicago",
"San Diego Comic Con",
"San Diego Comic Con (Staff)",
"Pokémon Rocks America",
"Games Expo",
"Gen Con",
"7-Eleven",
"EB Games",
"EB Games (Canada)",
"GameStop",
"Pokémon Center NY",
"Toys \"R\" Us",
"Build-A-Bear Workshop",
"Play! Pokémon",
"Play! Pokémon (Trick or Trade)",
"Play! Pokémon, Thank You Stamp",
"Play! Pokémon Prize Pack",
"Play! Pokémon Prize Pack (Left Stamp)",
"Play! Pokémon Prize Pack (Right Stamp)",
"Play! Pokémon Prize Pack (Right Stamp), Non-holo",
"Play! Pokémon Prize Pack, Cosmos Holo",
"Play! Pokémon Prize Pack, Cosmos Reverse Holo",
"Play! Pokémon Prize Pack, Non-holo",
"Play! Pokémon Prize Pack, Vertical Line Holo",
"Play! Pokémon Prize Pack, Vertical Line Reverse Holo",
"World Championships",
"World Championships (Staff)",
"World Championships (Top Thirty-Two)",
"Regional Championships",
"Regional Championships (2004-2009)",
"Regional Championships (2009-2010)",
"Regional Championships (2010-2011)",
"Regional Championships (2011-2012)",
"Regional Championships (2011-2012) (Staff)",
"Regional Championships (2012-2024)",
"Regional Championships (2012-2024) (Staff)",
"Regional Championships (Staff)",
"Regional Championships (2004-2009) (Staff)",
"Regional Championships (2010-2011) (Staff)",
"Championships Europe",
"Championships Europe (Staff)",
"Championships Latin America",
"Championships Latin America (Staff)",
"Championships North America",
"Championships North America (Staff)",
"Championships Oceania",
"National Championships",
"National Championships (Staff)",
"State/Prov./Ter. Championships",
"State/Prov./Ter. Championships (Staff)",
"City Championships",
"City Championships (Staff)",
"Paldean Fates Stamp",
"Shrouded Fable Stamp",
"Prismatic Evolutions Stamp (Left Stamp)",
"Black Bolt Stamp",
"White Flare Stamp",
"Astral Radiance Stamp",
"Brilliant Stars Stamp",
"Celestial Storm Stamp",
"Cosmic Eclipse Stamp",
"Darkness Ablaze Stamp",
"Destined Rivals Stamp",
"Detective Pikachu Stamp",
"Dragon Vault Stamp",
"E3 Stamp",
"EX Delta Species Stamp",
"Forbidden Light Stamp",
"Iono Zone Stamp",
"Journey Together Stamp",
"Legendary Pokémon Stamp",
"Lost Origin Stamp",
"Lost Thunder Stamp",
"Mega Evolution Stamp",
"Obsidian Flames Stamp",
"Paldea Evolved Stamp",
"Paradox Rift Stamp",
"Phantasmal Flames Stamp",
"Prismatic Evolutions Stamp",
"Rebel Clash Stamp",
"Scarlet & Violet 151 Stamp",
"Scarlet & Violet Stamp",
"Silver Tempest Stamp",
"Stellar Crown Stamp",
"Surging Sparks Stamp",
"Sword & Shield Stamp",
"Team Up Stamp",
"Temporal Forces Stamp",
"Thank You Stamp",
"Twilight Masquerade Stamp",
"Ultra Prism Stamp",
"Unbroken Bonds Stamp",
"Unified Minds Stamp",
"Vivid Voltage Stamp",
"Winner Stamp",
"WOTC Stamp",
"Jumbo Size",
"25th Anniversary, Jumbo Size",
"Jumbo Size (Redacted Print)",
"Jumbo Size, Cracked Ice Holo",
"Normal Holo, Jumbo Size",
"Surging Sparks Stamp, Jumbo Size",
"Prismatic Evolutions Stamp (Left Stamp), Jumbo Size",
"Paldean Fates Stamp, Jumbo Size",
"Astral Radiance Stamp, Jumbo Size",
"Brilliant Stars Stamp, Jumbo Size",
"Darkness Ablaze Stamp, Jumbo Size",
"Journey Together Stamp, Jumbo Size",
"Legendary Pokémon Stamp, Jumbo Size",
"Lost Origin Stamp, Jumbo Size",
"Prismatic Evolutions Stamp, Jumbo Size",
"Silver Tempest Stamp, Jumbo Size",
"Stellar Crown Stamp, Jumbo Size",
"Sword & Shield Stamp, Jumbo Size",
"Temporal Forces Stamp, Jumbo Size",
"Twilight Masquerade Stamp, Jumbo Size",
"Vivid Voltage Stamp, Jumbo Size",
"Winner Stamp, Jumbo Size",
"Battle Academy 2020 (Charizard 1)",
"Battle Academy 2020 (Charizard 2)",
"Battle Academy 2020 (Charizard 3)",
"Battle Academy 2020 (Charizard 4)",
"Battle Academy 2020 (Charizard 5)",
"Battle Academy 2020 (Charizard 6)",
"Battle Academy 2020 (Charizard 7)",
"Battle Academy 2020 (Charizard 8)",
"Battle Academy 2020 (Charizard 9)",
"Battle Academy 2020 (Charizard 10)",
"Battle Academy 2020 (Charizard 11)",
"Battle Academy 2020 (Charizard 12)",
"Battle Academy 2020 (Charizard 13)",
"Battle Academy 2020 (Charizard 14)",
"Battle Academy 2020 (Charizard 15)",
"Battle Academy 2020 (Charizard 17)",
"Battle Academy 2020 (Charizard 16)",
"Battle Academy 2020 (Charizard 18)",
"Battle Academy 2020 (Charizard 19)",
"Battle Academy 2020 (Charizard 20)",
"Battle Academy 2020 (Charizard 21)",
"Battle Academy 2020 (Charizard 22)",
"Battle Academy 2020 (Charizard 23)",
"Battle Academy 2020 (Charizard 24)",
"Battle Academy 2020 (Charizard 25)",
"Battle Academy 2020 (Charizard 26)",
"Battle Academy 2020 (Charizard 27)",
"Battle Academy 2020 (Charizard 28)",
"Battle Academy 2020 (Charizard 29)",
"Battle Academy 2020 (Charizard 30)",
"Battle Academy 2020 (Charizard 31)",
"Battle Academy 2020 (Charizard 32)",
"Battle Academy 2020 (Charizard 33)",
"Battle Academy 2020 (Charizard 34)",
"Battle Academy 2020 (Charizard 35)",
"Battle Academy 2020 (Charizard 36)",
"Battle Academy 2020 (Charizard 37)",
"Battle Academy 2020 (Charizard 38)",
"Battle Academy 2020 (Charizard 39)",
"Battle Academy 2020 (Charizard 40)",
"Battle Academy 2020 (Charizard 41)",
"Battle Academy 2020 (Charizard 42)",
"Battle Academy 2020 (Charizard 43)",
"Battle Academy 2020 (Charizard 44)",
"Battle Academy 2020 (Charizard 45)",
"Battle Academy 2020 (Charizard 46)",
"Battle Academy 2020 (Charizard 47)",
"Battle Academy 2020 (Charizard 48)",
"Battle Academy 2020 (Charizard 49)",
"Battle Academy 2020 (Charizard 50)",
"Battle Academy 2020 (Charizard 51)",
"Battle Academy 2020 (Charizard 52)",
"Battle Academy 2020 (Charizard 53)",
"Battle Academy 2020 (Charizard 54)",
"Battle Academy 2020 (Charizard 55)",
"Battle Academy 2020 (Charizard 56)",
"Battle Academy 2020 (Charizard 57)",
"Battle Academy 2020 (Charizard 58)",
"Battle Academy 2020 (Charizard 59)",
"Battle Academy 2020 (Charizard 60)",
"Battle Academy 2020 (Mewtwo)",
"Battle Academy 2020 (Pikachu 1)",
"Battle Academy 2020 (Pikachu 2)",
"Battle Academy 2020 (Pikachu 3)",
"Battle Academy 2020 (Pikachu 4)",
"Battle Academy 2020 (Pikachu 5)",
"Battle Academy 2020 (Pikachu 6)",
"Battle Academy 2020 (Pikachu 7)",
"Battle Academy 2020 (Pikachu 8)",
"Battle Academy 2020 (Pikachu 9)",
"Battle Academy 2020 (Pikachu 10)",
"Battle Academy 2020 (Pikachu 11)",
"Battle Academy 2020 (Pikachu 12)",
"Battle Academy 2020 (Pikachu 13)",
"Battle Academy 2020 (Pikachu 14)",
"Battle Academy 2020 (Pikachu 15)",
"Battle Academy 2020 (Pikachu 16)",
"Battle Academy 2020 (Pikachu 17)",
"Battle Academy 2020 (Pikachu 18)",
"Battle Academy 2020 (Pikachu 19)",
"Battle Academy 2020 (Pikachu 20)",
"Battle Academy 2020 (Pikachu 21)",
"Battle Academy 2020 (Pikachu 22)",
"Battle Academy 2020 (Pikachu 23)",
"Battle Academy 2020 (Pikachu 24)",
"Battle Academy 2020 (Pikachu 25)",
"Battle Academy 2020 (Pikachu 26)",
"Battle Academy 2020 (Pikachu 27)",
"Battle Academy 2020 (Pikachu 28)",
"Battle Academy 2020 (Pikachu 29)",
"Battle Academy 2020 (Pikachu 30)",
"Battle Academy 2020 (Pikachu 31)",
"Battle Academy 2020 (Pikachu 32)",
"Battle Academy 2020 (Pikachu 33)",
"Battle Academy 2020 (Pikachu 34)",
"Battle Academy 2020 (Pikachu 35)",
"Battle Academy 2020 (Pikachu 36)",
"Battle Academy 2020 (Pikachu 37)",
"Battle Academy 2020 (Pikachu 38)",
"Battle Academy 2020 (Pikachu 39)",
"Battle Academy 2020 (Pikachu 40)",
"Battle Academy 2020 (Pikachu 41)",
"Battle Academy 2020 (Pikachu 42)",
"Battle Academy 2020 (Pikachu 43)",
"Battle Academy 2020 (Pikachu 44)",
"Battle Academy 2020 (Pikachu 45)",
"Battle Academy 2020 (Pikachu 46)",
"Battle Academy 2020 (Pikachu 47)",
"Battle Academy 2020 (Pikachu 48)",
"Battle Academy 2020 (Pikachu 49)",
"Battle Academy 2020 (Pikachu 50)",
"Battle Academy 2020 (Pikachu 51)",
"Battle Academy 2020 (Pikachu 52)",
"Battle Academy 2020 (Pikachu 53)",
"Battle Academy 2020 (Pikachu 54)",
"Battle Academy 2020 (Pikachu 55)",
"Battle Academy 2020 (Pikachu 56)",
"Battle Academy 2020 (Pikachu 57)",
"Battle Academy 2020 (Pikachu 58)",
"Battle Academy 2020 (Pikachu 59)",
"Battle Academy 2020 (Pikachu 60)",
"Battle Academy 2022 (Cinderace 1)",
"Battle Academy 2022 (Cinderace 2)",
"Battle Academy 2022 (Cinderace 3)",
"Battle Academy 2022 (Cinderace 4)",
"Battle Academy 2022 (Cinderace 5)",
"Battle Academy 2022 (Cinderace 6)",
"Battle Academy 2022 (Cinderace 7)",
"Battle Academy 2022 (Cinderace 8)",
"Battle Academy 2022 (Cinderace 9)",
"Battle Academy 2022 (Cinderace 10)",
"Battle Academy 2022 (Cinderace 11)",
"Battle Academy 2022 (Cinderace 12)",
"Battle Academy 2022 (Cinderace 13)",
"Battle Academy 2022 (Cinderace 14)",
"Battle Academy 2022 (Cinderace 15)",
"Battle Academy 2022 (Cinderace 16)",
"Battle Academy 2022 (Cinderace 17)",
"Battle Academy 2022 (Cinderace 18)",
"Battle Academy 2022 (Cinderace 19)",
"Battle Academy 2022 (Cinderace 20)",
"Battle Academy 2022 (Cinderace 21)",
"Battle Academy 2022 (Cinderace 22)",
"Battle Academy 2022 (Cinderace 23)",
"Battle Academy 2022 (Cinderace 24)",
"Battle Academy 2022 (Cinderace 25)",
"Battle Academy 2022 (Cinderace 26)",
"Battle Academy 2022 (Cinderace 27)",
"Battle Academy 2022 (Cinderace 28)",
"Battle Academy 2022 (Cinderace 29)",
"Battle Academy 2022 (Cinderace 30)",
"Battle Academy 2022 (Cinderace 31)",
"Battle Academy 2022 (Cinderace 32)",
"Battle Academy 2022 (Cinderace 33)",
"Battle Academy 2022 (Cinderace 34)",
"Battle Academy 2022 (Cinderace 35)",
"Battle Academy 2022 (Cinderace 36)",
"Battle Academy 2022 (Cinderace 37)",
"Battle Academy 2022 (Cinderace 38)",
"Battle Academy 2022 (Cinderace 39)",
"Battle Academy 2022 (Cinderace 40)",
"Battle Academy 2022 (Cinderace 41)",
"Battle Academy 2022 (Cinderace 42)",
"Battle Academy 2022 (Cinderace 43)",
"Battle Academy 2022 (Cinderace 44)",
"Battle Academy 2022 (Cinderace 45)",
"Battle Academy 2022 (Cinderace 46)",
"Battle Academy 2022 (Cinderace 47)",
"Battle Academy 2022 (Cinderace 48)",
"Battle Academy 2022 (Cinderace 49)",
"Battle Academy 2022 (Cinderace 50)",
"Battle Academy 2022 (Cinderace 51)",
"Battle Academy 2022 (Cinderace 52)",
"Battle Academy 2022 (Cinderace 53)",
"Battle Academy 2022 (Cinderace 54)",
"Battle Academy 2022 (Cinderace 55)",
"Battle Academy 2022 (Cinderace 56)",
"Battle Academy 2022 (Cinderace 57)",
"Battle Academy 2022 (Cinderace 58)",
"Battle Academy 2022 (Cinderace 59)",
"Battle Academy 2022 (Cinderace 60)",
"Battle Academy 2022 (Eevee)",
"Battle Academy 2022 (Pikachu 1)",
"Battle Academy 2022 (Pikachu 2)",
"Battle Academy 2022 (Pikachu 3)",
"Battle Academy 2022 (Pikachu 4)",
"Battle Academy 2022 (Pikachu 5)",
"Battle Academy 2022 (Pikachu 6)",
"Battle Academy 2022 (Pikachu 7)",
"Battle Academy 2022 (Pikachu 8)",
"Battle Academy 2022 (Pikachu 9)",
"Battle Academy 2022 (Pikachu 10)",
"Battle Academy 2022 (Pikachu 11)",
"Battle Academy 2022 (Pikachu 12)",
"Battle Academy 2022 (Pikachu 13)",
"Battle Academy 2022 (Pikachu 14)",
"Battle Academy 2022 (Pikachu 15)",
"Battle Academy 2022 (Pikachu 16)",
"Battle Academy 2022 (Pikachu 17)",
"Battle Academy 2022 (Pikachu 18)",
"Battle Academy 2022 (Pikachu 19)",
"Battle Academy 2022 (Pikachu 20)",
"Battle Academy 2022 (Pikachu 21)",
"Battle Academy 2022 (Pikachu 22)",
"Battle Academy 2022 (Pikachu 23)",
"Battle Academy 2022 (Pikachu 24)",
"Battle Academy 2022 (Pikachu 25)",
"Battle Academy 2022 (Pikachu 26)",
"Battle Academy 2022 (Pikachu 27)",
"Battle Academy 2022 (Pikachu 28)",
"Battle Academy 2022 (Pikachu 29)",
"Battle Academy 2022 (Pikachu 30)",
"Battle Academy 2022 (Pikachu 31)",
"Battle Academy 2022 (Pikachu 32)",
"Battle Academy 2022 (Pikachu 33)",
"Battle Academy 2022 (Pikachu 34)",
"Battle Academy 2022 (Pikachu 35)",
"Battle Academy 2022 (Pikachu 36)",
"Battle Academy 2022 (Pikachu 37)",
"Battle Academy 2022 (Pikachu 38)",
"Battle Academy 2022 (Pikachu 39)",
"Battle Academy 2022 (Pikachu 40)",
"Battle Academy 2022 (Pikachu 41)",
"Battle Academy 2022 (Pikachu 42)",
"Battle Academy 2022 (Pikachu 43)",
"Battle Academy 2022 (Pikachu 44)",
"Battle Academy 2022 (Pikachu 45)",
"Battle Academy 2022 (Pikachu 46)",
"Battle Academy 2022 (Pikachu 47)",
"Battle Academy 2022 (Pikachu 48)",
"Battle Academy 2022 (Pikachu 49)",
"Battle Academy 2022 (Pikachu 50)",
"Battle Academy 2022 (Pikachu 51)",
"Battle Academy 2022 (Pikachu 52)",
"Battle Academy 2022 (Pikachu 53)",
"Battle Academy 2022 (Pikachu 54)",
"Battle Academy 2022 (Pikachu 55)",
"Battle Academy 2022 (Pikachu 56)",
"Battle Academy 2022 (Pikachu 57)",
"Battle Academy 2022 (Pikachu 58)",
"Battle Academy 2022 (Pikachu 59)",
"Battle Academy 2022 (Pikachu 60)",
"Battle Academy 2024 (Armarouge 1)",
"Battle Academy 2024 (Armarouge 2)",
"Battle Academy 2024 (Armarouge 3)",
"Battle Academy 2024 (Armarouge 4)",
"Battle Academy 2024 (Armarouge 5)",
"Battle Academy 2024 (Armarouge 6)",
"Battle Academy 2024 (Armarouge 7)",
"Battle Academy 2024 (Armarouge 8)",
"Battle Academy 2024 (Armarouge 9)",
"Battle Academy 2024 (Armarouge 10)",
"Battle Academy 2024 (Armarouge 11)",
"Battle Academy 2024 (Armarouge 12)",
"Battle Academy 2024 (Armarouge 13)",
"Battle Academy 2024 (Armarouge 14)",
"Battle Academy 2024 (Armarouge 15)",
"Battle Academy 2024 (Armarouge 16)",
"Battle Academy 2024 (Armarouge 17)",
"Battle Academy 2024 (Armarouge 18)",
"Battle Academy 2024 (Armarouge 19)",
"Battle Academy 2024 (Armarouge 20)",
"Battle Academy 2024 (Armarouge 21)",
"Battle Academy 2024 (Armarouge 22)",
"Battle Academy 2024 (Armarouge 23)",
"Battle Academy 2024 (Armarouge 24)",
"Battle Academy 2024 (Armarouge 25)",
"Battle Academy 2024 (Armarouge 26)",
"Battle Academy 2024 (Armarouge 27)",
"Battle Academy 2024 (Armarouge 28)",
"Battle Academy 2024 (Armarouge 29)",
"Battle Academy 2024 (Armarouge 30)",
"Battle Academy 2024 (Armarouge 31)",
"Battle Academy 2024 (Armarouge 32)",
"Battle Academy 2024 (Armarouge 33)",
"Battle Academy 2024 (Armarouge 34)",
"Battle Academy 2024 (Armarouge 35)",
"Battle Academy 2024 (Armarouge 36)",
"Battle Academy 2024 (Armarouge 37)",
"Battle Academy 2024 (Armarouge 38)",
"Battle Academy 2024 (Armarouge 39)",
"Battle Academy 2024 (Armarouge 40)",
"Battle Academy 2024 (Armarouge 41)",
"Battle Academy 2024 (Armarouge 42)",
"Battle Academy 2024 (Armarouge 43)",
"Battle Academy 2024 (Armarouge 44)",
"Battle Academy 2024 (Armarouge 45)",
"Battle Academy 2024 (Armarouge 46)",
"Battle Academy 2024 (Armarouge 47)",
"Battle Academy 2024 (Armarouge 48)",
"Battle Academy 2024 (Armarouge 49)",
"Battle Academy 2024 (Armarouge 50)",
"Battle Academy 2024 (Armarouge 51)",
"Battle Academy 2024 (Armarouge 52)",
"Battle Academy 2024 (Armarouge 53)",
"Battle Academy 2024 (Armarouge 54)",
"Battle Academy 2024 (Armarouge 55)",
"Battle Academy 2024 (Armarouge 56)",
"Battle Academy 2024 (Armarouge 57)",
"Battle Academy 2024 (Armarouge 58)",
"Battle Academy 2024 (Armarouge 59)",
"Battle Academy 2024 (Armarouge 60)",
"Battle Academy 2024 (Darkrai)",
"Battle Academy 2024 (Pikachu 1)",
"Battle Academy 2024 (Pikachu 2)",
"Battle Academy 2024 (Pikachu 3)",
"Battle Academy 2024 (Pikachu 4)",
"Battle Academy 2024 (Pikachu 5)",
"Battle Academy 2024 (Pikachu 6)",
"Battle Academy 2024 (Pikachu 7)",
"Battle Academy 2024 (Pikachu 8)",
"Battle Academy 2024 (Pikachu 9)",
"Battle Academy 2024 (Pikachu 10)",
"Battle Academy 2024 (Pikachu 11)",
"Battle Academy 2024 (Pikachu 12)",
"Battle Academy 2024 (Pikachu 13)",
"Battle Academy 2024 (Pikachu 14)",
"Battle Academy 2024 (Pikachu 15)",
"Battle Academy 2024 (Pikachu 16)",
"Battle Academy 2024 (Pikachu 17)",
"Battle Academy 2024 (Pikachu 18)",
"Battle Academy 2024 (Pikachu 19)",
"Battle Academy 2024 (Pikachu 20)",
"Battle Academy 2024 (Pikachu 21)",
"Battle Academy 2024 (Pikachu 22)",
"Battle Academy 2024 (Pikachu 23)",
"Battle Academy 2024 (Pikachu 24)",
"Battle Academy 2024 (Pikachu 25)",
"Battle Academy 2024 (Pikachu 26)",
"Battle Academy 2024 (Pikachu 27)",
"Battle Academy 2024 (Pikachu 28)",
"Battle Academy 2024 (Pikachu 29)",
"Battle Academy 2024 (Pikachu 30)",
"Battle Academy 2024 (Pikachu 31)",
"Battle Academy 2024 (Pikachu 32)",
"Battle Academy 2024 (Pikachu 33)",
"Battle Academy 2024 (Pikachu 34)",
"Battle Academy 2024 (Pikachu 35)",
"Battle Academy 2024 (Pikachu 36)",
"Battle Academy 2024 (Pikachu 37)",
"Battle Academy 2024 (Pikachu 38)",
"Battle Academy 2024 (Pikachu 39)",
"Battle Academy 2024 (Pikachu 40)",
"Battle Academy 2024 (Pikachu 41)",
"Battle Academy 2024 (Pikachu 42)",
"Battle Academy 2024 (Pikachu 43)",
"Battle Academy 2024 (Pikachu 44)",
"Battle Academy 2024 (Pikachu 45)",
"Battle Academy 2024 (Pikachu 46)",
"Battle Academy 2024 (Pikachu 47)",
"Battle Academy 2024 (Pikachu 48)",
"Battle Academy 2024 (Pikachu 49)",
"Battle Academy 2024 (Pikachu 50)",
"Battle Academy 2024 (Pikachu 51)",
"Battle Academy 2024 (Pikachu 52)",
"Battle Academy 2024 (Pikachu 53)",
"Battle Academy 2024 (Pikachu 54)",
"Battle Academy 2024 (Pikachu 55)",
"Battle Academy 2024 (Pikachu 56)",
"Battle Academy 2024 (Pikachu 57)",
"Battle Academy 2024 (Pikachu 58)",
"Battle Academy 2024 (Pikachu 59)",
"Battle Academy 2024 (Pikachu 60)",
"SM Trainer Kit (Alolan Ninetales 1)",
"SM Trainer Kit (Alolan Ninetales 10)",
"SM Trainer Kit (Alolan Ninetales 11)",
"SM Trainer Kit (Alolan Ninetales 12)",
"SM Trainer Kit (Alolan Ninetales 13)",
"SM Trainer Kit (Alolan Ninetales 14)",
"SM Trainer Kit (Alolan Ninetales 15)",
"SM Trainer Kit (Alolan Ninetales 16)",
"SM Trainer Kit (Alolan Ninetales 17)",
"SM Trainer Kit (Alolan Ninetales 18)",
"SM Trainer Kit (Alolan Ninetales 19)",
"SM Trainer Kit (Alolan Ninetales 2)",
"SM Trainer Kit (Alolan Ninetales 20)",
"SM Trainer Kit (Alolan Ninetales 21)",
"SM Trainer Kit (Alolan Ninetales 22)",
"SM Trainer Kit (Alolan Ninetales 23)",
"SM Trainer Kit (Alolan Ninetales 24)",
"SM Trainer Kit (Alolan Ninetales 25)",
"SM Trainer Kit (Alolan Ninetales 26)",
"SM Trainer Kit (Alolan Ninetales 27)",
"SM Trainer Kit (Alolan Ninetales 28)",
"SM Trainer Kit (Alolan Ninetales 29)",
"SM Trainer Kit (Alolan Ninetales 3)",
"SM Trainer Kit (Alolan Ninetales 30)",
"SM Trainer Kit (Alolan Ninetales 4)",
"SM Trainer Kit (Alolan Ninetales 5)",
"SM Trainer Kit (Alolan Ninetales 6)",
"SM Trainer Kit (Alolan Ninetales 7)",
"SM Trainer Kit (Alolan Ninetales 8)",
"SM Trainer Kit (Alolan Ninetales 9)",
"SM Trainer Kit (Alolan Sandslash 1)",
"SM Trainer Kit (Alolan Sandslash 10)",
"SM Trainer Kit (Alolan Sandslash 11)",
"SM Trainer Kit (Alolan Sandslash 12)",
"SM Trainer Kit (Alolan Sandslash 13)",
"SM Trainer Kit (Alolan Sandslash 14)",
"SM Trainer Kit (Alolan Sandslash 15)",
"SM Trainer Kit (Alolan Sandslash 16)",
"SM Trainer Kit (Alolan Sandslash 17)",
"SM Trainer Kit (Alolan Sandslash 18)",
"SM Trainer Kit (Alolan Sandslash 19)",
"SM Trainer Kit (Alolan Sandslash 2)",
"SM Trainer Kit (Alolan Sandslash 20)",
"SM Trainer Kit (Alolan Sandslash 21)",
"SM Trainer Kit (Alolan Sandslash 22)",
"SM Trainer Kit (Alolan Sandslash 23)",
"SM Trainer Kit (Alolan Sandslash 24)",
"SM Trainer Kit (Alolan Sandslash 25)",
"SM Trainer Kit (Alolan Sandslash 26)",
"SM Trainer Kit (Alolan Sandslash 27)",
"SM Trainer Kit (Alolan Sandslash 28)",
"SM Trainer Kit (Alolan Sandslash 29)",
"SM Trainer Kit (Alolan Sandslash 3)",
"SM Trainer Kit (Alolan Sandslash 30)",
"SM Trainer Kit (Alolan Sandslash 4)",
"SM Trainer Kit (Alolan Sandslash 5)",
"SM Trainer Kit (Alolan Sandslash 6)",
"SM Trainer Kit (Alolan Sandslash 7)",
"SM Trainer Kit (Alolan Sandslash 8)",
"SM Trainer Kit (Alolan Sandslash 9)",
"WC Deck 2004 (Blaziken Tech: Chris Fulop)",
"WC Deck 2004 (Magma Spirit: Tsuguyoshi Yamato)",
"WC Deck 2004 (Rocky Beach: Reed Weichler)",
"WC Deck 2004 (Team Rushdown: Kevin Nguyen)",
"WC Deck 2005 (Bright Aura: Curran Hill)",
"WC Deck 2005 (Dark Tyranitar: Takashi Yoneda)",
"WC Deck 2005 (King of the West: Michael Gonzalez)",
"WC Deck 2005 (Queendom: Jeremy Maron)",
"WC Deck 2006 (B-L-S: Hiroki Yano)",
"WC Deck 2006 (Eeveelutions: Jimmy Ballard)",
"WC Deck 2006 (Mewtrick: Jason Klaczynski)",
"WC Deck 2006 (Suns & Moons: Miska Saari)",
"WC Deck 2007 (Flyvees: Jun Hasebe)",
"WC Deck 2007 (Legendary Ascent: Tom Roos)",
"WC Deck 2007 (Rambolt: Jeremy Scharff-Kim)",
"WC Deck 2007 (Swift Empoleon: Akira Miyazaki)",
"WC Deck 2008 (Bliss Control: Paul Atanassov)",
"WC Deck 2008 (Empotech: Dylan Lefavour)",
"WC Deck 2008 (Intimidation: Tristan Robinson)",
"WC Deck 2008 (Psychic Lock: Jason Klaczynski)",
"WC Deck 2009 (Crowned Tiger: Tsubasa Nakamura)",
"WC Deck 2009 (Luxdrill: Stephen Silvestro)",
"WC Deck 2009 (Queengar: Jason Martinez)",
"WC Deck 2009 (Stallgon: David Cohen)",
"WC Deck 2010 (Boltevoir: Michael Pramawat)",
"WC Deck 2010 (Happy Luck: Mychael Bryan)",
"WC Deck 2010 (LuxChomp of the Spirit: Yuta Komatsuda)",
"WC Deck 2010 (Power Cottonweed: Yuka Furusawa)",
"WC Deck 2011 (Megazone: Gustavo Wada)",
"WC Deck 2011 (Reshiphlosion: Christopher Kan)",
"WC Deck 2011 (The Truth: Ross Cawthon)",
"WC Deck 2011 (Twinboar: David Cohen)",
"WC Deck 2012 (CMT: Zachary Bokhari)",
"WC Deck 2012 (Eeltwo: Chase Moloney)",
"WC Deck 2012 (Pesadelo Prism: Igor Costa)",
"WC Deck 2012 (Terraki-Mewtwo: Shuto Itagaki)",
"WC Deck 2013 (American Gothic: Ian Whiton)",
"WC Deck 2013 (Anguille Sous Roche: Clément Lamberton)",
"WC Deck 2013 (Darkrai: Jason Klaczynski)",
"WC Deck 2013 (Ultimate Team Plasma: Yugo Sato)",
"WC Deck 2014 (Crazy Punch: Michikazu Tsuda)",
"WC Deck 2014 (Emerald King: Andrew Estrada)",
"WC Deck 2014 (Plasma Power: Haruto Kobayashi)",
"WC Deck 2014 (Trevgor: Trent Orndorff)",
"WC Deck 2015 (HonorStoise: Jacob Van Wagner)",
"WC Deck 2015 (Primal Groudon: Alejandro Ng-Guzman)",
"WC Deck 2015 (Punches 'n' Bites: Patrick Martinez)",
"WC Deck 2015 (The Flying Hammer: Rowan Stavenow)",
"WC Deck 2016 (Bebe Deck: Jesper Eriksen)",
"WC Deck 2016 (Black Dragon: Shuntu Sadahiro)",
"WC Deck 2016 (Magical Symphony: Shintaro Ito)",
"WC Deck 2016 (Ninja Blitz: Cody Walinski)",
"WC Deck 2017 (Golisodor: Naoto Suzuki)",
"WC Deck 2017 (Ice Path FTW: Zachary Bokhari)",
"WC Deck 2017 (Infinite Force: Diego Cassiraga)",
"WC Deck 2017 (Samurai Sniper: Kabu Fukase)",
"WC Deck 2018 (Buzzroc: Naohito Inoue)",
"WC Deck 2018 (Dragones y Sombras: Pedro Eugenio Torres)",
"WC Deck 2018 (Garbanette: Magnus Pedersen)",
"WC Deck 2018 (Victory Map: Robin Schulz)",
"WC Deck 2019 (Fire Box: Kaya Lichtleitner)",
"WC Deck 2019 (Mind Blown: Shintaro Ito)",
"WC Deck 2019 (Perfection: Henry Brand)",
"WC Deck 2019 (Pikarom Judge: Haruki Miyamoto)",
"WC Deck 2022 (ADP: Ondřej Škubal)",
"WC Deck 2022 (Cheryl Again: Sebastian Lashmet)",
"WC Deck 2022 (Ice Rider Palkia: Rikuto Ohashi)",
"WC Deck 2022 (The Shape of Mew: André Chiasson)",
"WC Deck 2023 (Colorless Lugia: Gabriel Fernandez)",
"WC Deck 2023 (Lost Box Kyogre: Shao Tong Yen)",
"WC Deck 2023 (Mew's Revenge: Vance Kelley)",
"WC Deck 2023 (Psychic Elegance: Tord Reklev)",
"Battle Road Autumn 2007-",
"Battle Road Autumn 2008-",
"Battle Road Autumn 2010-",
"Battle Road Autumn 2011 (1st Place)",
"Battle Road Autumn 2011 (2nd Place)",
"Battle Road Autumn 2011 (3rd Place)",
"Battle Road Autumn 2012 (1st Place)",
"Battle Road Autumn 2012 (2nd Place)",
"Battle Road Autumn 2012 (3rd Place)",
"Battle Road Spring 2008-",
"Battle Road Spring 2009-",
"Battle Road Spring 2010-",
"Battle Road Spring 2012 (1st Place)",
"Battle Road Spring 2012 (2nd Place)",
"Battle Road Spring 2012 (3rd Place)",
"Battle Road Spring 2013 (1st Place)",
"Battle Road Spring 2013 (2nd Place)",
"League Challenge (1st Place)",
"League Challenge (2nd Place)",
"League Challenge (3rd Place)",
"League Challenge (4th Place)",
"Cosmos Holo",
"Trick or Trade",
"Prerelease",
"Prerelease (Staff)",
"Prerelease, Starlight Holo",
"Poké Ball Holo",
"Master Ball Holo",
"Cosmos Reverse Holo",
"Arena Cup (Staff)",
"League Cup (Staff)",
"Origins (Staff)",
"10th Anniversary",
"20th Anniversary",
"25th Anniversary",
"Burger King Collection",
"Cosmos Holo (1999 Copyright)",
"Countdown Calendar",
"Cracked Ice Holo",
"Double Album Box",
"European POP Tournament",
"Glossy",
"Gold Border",
"Gym",
"Gym Challenge",
"Holiday Calendar",
"InQuest",
"International Challenge",
"League Cup",
"Metal Card",
"Mirage Holo",
"Mirror Holo",
"Mirror Reverse Holo",
"No e-Reader",
"No e-Reader, Holo",
"No e-Reader, Non-holo",
"Normal (Gold Signature)",
"Origins",
"Parallel Set (Confetti Holo)",
"Player Rewards Program",
"Pokémon Center",
"Pokémon Club",
"Pokémon Day",
"Pokémon Horizons: The Series",
"Pokémon League",
"Pokémon Together",
"PokéTour",
"Prerelease, Starlight Holo",
"Professor Program",
"Rain City Showcase",
"Reverse Holo (High Plains Pattern)",
"Reverse Holo (Meadow Pattern)",
"Scryre",
"Sequin Holo",
"Sheen Holo",
"Speckle Holo",
"Stadium Challenge",
"Starlight Holo",
"Tinsel Holo",
"Unpeeled Card (Bidoof)",
"Unpeeled Card (Numel)",
"Unpeeled Card (Spinarak)",
"Vertical Line Holo",
"Vertical Sheen Holo",
"Water Web Holo",
"Normal Holo (Meadow Pattern)",
"Normal Holo (High Plains Pattern)",
]